name: vite build

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build-test

    # - name: Deploy
    #   uses: JamesIves/github-pages-deploy-action@v4
    #   with:
    #     folder: docs # The folder the action should deploy.

    - name: Archive
      uses: actions/upload-pages-artifact@v2
      with:
        name: github-pages
        path: docs/

    - name: Deploy
      uses: actions/deploy-pages@v2
      with:
        token: ${{ github.token }}        